version: 2

jobs:
  build:
    docker:
      - image: quay.io/rust-lang-ja/circleci:mdbook
    parallelism: 1
    steps:
      - checkout
      # Remove .gitconfig added by Circle CI as cargo doesn't support ssh authorization
      - run: rm -f ~/.gitconfig
      - run: rm -rf rust-toolchain docs
      - run: rustc -V
      - run: mdbook -V
      - run: mdbook test
      - run: mdbook build --dest-dir docs
      - run: cargo run --bin lfp src
      # TODO: Run link2print here. (See ci/build.sh on the master branch)
      # - run: TODO
      - store_artifacts:
          path: docs
      # Restore a deleted file.
      - run: git checkout rust-toolchain
      - deploy:
          name: If master-ja branch, publish to GitHub Page
          command: |
            if [ "x_${CIRCLE_BRANCH}" == "x_master-ja" ]; then
              git config user.name "bn-e (CircleCI)"
              git config user.email "bn-e@hibaridb.org"
              ./tools/circleci/push-to-master-ja.sh
            fi
